WIP: support for ebs snapshots
grid-x/aws-auto-snapshot pull request #4
Opened 2017-11-07 17:28 UTC by jhedev

2017-11-15 11:06 UTC, philippfranke requested changes
All about comments...

2017-11-15 11:06 UTC, philippfranke commented on cmd/snapshotter/main.go
> +type Snapshotter interface {
👵: Golinter likes to see a comment here.

2017-11-15 11:06 UTC, philippfranke commented on pkg/snapshot/ec2/ec2.go
> +
👵: Golinter likes to see a comment here.

2017-11-15 11:06 UTC, philippfranke commented on pkg/snapshot/ec2/ec2.go
> +type Opt func(*SnapshotManager)
👵: Golinter likes to see a comment here.

2017-11-15 11:06 UTC, philippfranke commented on pkg/snapshot/ec2/ec2.go
> +func WithRetentionTag(t string) Opt {
👵: Golinter likes to see a comment here.

2017-11-15 11:06 UTC, philippfranke commented on pkg/snapshot/ec2/ec2.go
> +func WithBackupTag(t string) Opt {
👵: Golinter likes to see a comment here.

2017-11-15 11:06 UTC, philippfranke commented on pkg/snapshot/ec2/ec2.go
> +func WithSnapshotSuffix(suf string) Opt {
👵: Golinter likes to see a comment here.

2017-11-15 11:06 UTC, philippfranke commented on pkg/snapshot/ec2/ec2.go
> +func WithDeleteAfterTag(tag string) Opt {
👵: Golinter likes to see a comment here.

2017-11-15 11:06 UTC, philippfranke commented on pkg/snapshot/ec2/ec2.go
> +func NewSnapshotManager(client *ec2.EC2, opts ...Opt) *SnapshotManager {
👵: Golinter likes to see a comment here.

2017-11-15 11:06 UTC, philippfranke commented on pkg/snapshot/ec2/ec2.go
> +func (smgr *SnapshotManager) Snapshot(ctx context.Context) error {
👵: Golinter likes to see a comment here.

2017-11-15 11:06 UTC, philippfranke commented on pkg/snapshot/ec2/ec2.go
> +func (smgr *SnapshotManager) Prune(ctx context.Context) error {
👵: Golinter likes to see a comment here.

2017-11-15 12:47 UTC, jhedev commented
Added linting to the CI and fixed all problems @philippfranke

2017-11-17 07:42 UTC, jhedev commented
ping @gq0 @philippfranke

2017-11-17 07:51 UTC, gq0 commented on glide.yaml
> +- package: gopkg.in/alecthomas/kingpin.v2
Oh, a new dependency.

2017-11-17 07:51 UTC, gq0 approved these changes
ad-hoc it looks good

2017-11-17 08:31 UTC, philippfranke approved these changes
👍  LGTM

2017-11-17 08:34 UTC, merged